### ISSUE TITLE
Add button should be disabled if field is empty

### ISSUE THREAD

**Issue by waldyrious** [santisbon/emojos#1]
Currently I get a pop-up saying "please fill out this fill out this field" on desktop, but on mobile that doesn't appear, and to compound on the issue, the color of the placeholder text is dark enough to lead me to think it was already filled with "mastodon.social". So I kept trying to press the "Add" button without any feedback.

**Comment by santisbon** [comment]
I get consistent behavior on desktop and mobile, both Safari and Chrome. If the required field is empty you get "Fill out this field" and the text for the placeholders "mastodon.social" and "Search" is greyed out, not black like normal text elsewhere.

![IMG_4789](https://github.com/santisbon/emojos/assets/3804335/d91fca03-744b-4cd2-9be8-a34c3c2d3749)
