### ISSUE TITLE
Add button wraps awkwardly

### ISSUE THREAD

**Issue by waldyrious** [santisbon/emojos#2]
Currently on mobile the "Add button" appears to the side of the corresponding input field (as expected), but on desktop for some reason it's wrapping, even though I have plenty of horizontal space available:

![image](https://github.com/santisbon/emojos/assets/478237/9720e087-55ce-42f5-b045-f2633caf3dac)

This is not bad per se (I think it's great that there's the possibility of wrapping when the horizontal space is limited) but it shouldn't happen given the width of my desktop viewport.

In any case, for the cases where wrapping _is_ needed, it should happen more gracefully, i.e. with some vertical space between the input box and the button. For example:

![image](https://github.com/santisbon/emojos/assets/478237/2db75853-458d-419c-a8c3-fabdeaf861dc)

**Comment by santisbon** [comment]
Which desktop browser are you using? Can't reproduce with Safari or Chrome.

**Comment by waldyrious** [comment]
I'm using Firefox. But I see the same in Vivaldi:

![image](https://github.com/santisbon/emojos/assets/478237/059df6b0-edd1-44a5-9cd7-d8be7c8397bb)

and Brave:

![image](https://github.com/santisbon/emojos/assets/478237/d5143419-30d5-4d23-97a9-eee0e7793f1c)

..both of which are based on Chromium :thinking:
