### ISSUE TITLE
Allow comparing multiple servers

### ISSUE THREAD

**Issue by waldyrious** [santisbon/emojos#3]
Right now one can only pick one server at a time to view their emojos. I think it would be great to have a comparison feature, where multiple servers could be selected on the sidebar (in checkbox mode rather than radio button mode), and the main area would have one column for each server.

Even better if there was a "highlight unique emojos" toggle in this comparison mode, which would highlight the unique emojos that each server has. Alternatively, this feature could dim out, or even hide, the duplicate ones.

**Comment by santisbon** [comment]
While that would be a nice feature to have it would not be possible in practice as each server has their own image file and short code for the same emoji. There's no reliable way to know if two emojis on different servers really are the same emoji just with a different image and short code.

**Comment by waldyrious** [comment]
Got it, thanks for the explanation!
